### ISSUE TITLE
Иконки для панели навигации

### ISSUE THREAD

**Issue by rustedhorse** [8clever/idle-spirit#1]
2 скрещенных меча (https://ru.freepik.com/free-vector/swords-knives-daggers-sharp-blades-flat-icon-set-isolated-vector-illustration_1158787.htm 2 сверху, но желательно не такой яркий + навершие сделать круглым)
Наковальня( https://ru.freepik.com/free-vector/blacksmith-flat-color-icons-set_3794893.htm#page=1&query=%D0%9D%D0%B0%D0%BA%D0%BE%D0%B2%D0%B0%D0%BB%D1%8C%D0%BD%D1%8F&position=39 примерно такую, нг чтобы под общую цветовую гамму подходила и без молотка и заготовки)
Кипящее зелье ( вообще все равно, только что цвет жижы сделать зеленым)
Вывеска магазина(на вывески должен быть нарисован такой тип весов https://ru.m.wikipedia.org/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:Balance_%C3%A0_tabac_1850.JPG)
Сумка ( https://ru.freepik.com/premium-vector/variety-of-bags_956777.htm#page=2&query=%D0%A1%D1%83%D0%BC%D0%BA%D0%B0&position=8 как тут рюкзак слева по середине, но одним цветом и без лямок. Цвет светлокоричневый)
Согнутая накаченная рука(будет использоваться для улучшений связанных с повышением уровня персонажей)
Знак доллара(будет донат магазином, поэтому просто чтобы хоть как-то вписывался в тематику минимализма+средневековье)

**Comment by mihailvityaev** [comment]
мечи:
![мечи2](https://user-images.githubusercontent.com/68809237/101240255-20377d80-36ff-11eb-8e25-070208ad3aab.png)

**Comment by mihailvityaev** [comment]
наковальня:
![наковальня](https://user-images.githubusercontent.com/68809237/101240569-07c86280-3701-11eb-8982-8f54d192ac37.png)

**Comment by mihailvityaev** [comment]
Зелья:
![зелье](https://user-images.githubusercontent.com/68809237/101241823-a3120580-370a-11eb-97b4-66b411d11e5f.png)
![зелье2](https://user-images.githubusercontent.com/68809237/101241825-a3aa9c00-370a-11eb-88f1-10fb4bc61d15.png)

**Comment by mihailvityaev** [comment]
Вывеска магазина:

![ебучий щит-Recovered4](https://user-images.githubusercontent.com/68809237/101261829-f3a95300-374a-11eb-9179-6a429245e61d.png)

**Comment by mihailvityaev** [comment]
рюкзак:
![ебучий рюкзак3](https://user-images.githubusercontent.com/68809237/101265676-5dc8f480-3759-11eb-95a2-184ee1389b3b.png)

**Comment by mihailvityaev** [comment]
доллар:
![деньга](https://user-images.githubusercontent.com/68809237/101281255-1a18ce00-37df-11eb-96fb-580cb5841e87.png)

**Comment by mihailvityaev** [comment]
зелье без крышки

![зелье3](https://user-images.githubusercontent.com/68809237/101281305-47657c00-37df-11eb-9644-b3a7ab96a937.png)

**Comment by mihailvityaev** [comment]
рюкзак новый:
![рюкзак3](https://user-images.githubusercontent.com/68809237/101281723-bb088880-37e1-11eb-99e4-9546b03e0c57.png)
