### ISSUE TITLE
Вкладка сражений(иконки)

### ISSUE THREAD

**Issue by rustedhorse** [8clever/idle-spirit#2]
Сердечко(индикатор здоровья воина)
![image](https://user-images.githubusercontent.com/24581080/101281023-d1144a00-37dd-11eb-961a-49d28e0231fa.png) 
Такое, но красное.
Меч(по сути можно будет взять 1 штуку из скрещенных мечей)
Латы (![image](https://user-images.githubusercontent.com/24581080/101281140-88a95c00-37de-11eb-9acb-220975d7a4a8.png) нужен такой тип, но сильно упрощённый и в серых тонах)
Монета( Обычная, золотых оттенков, но в плане лого думаю 
![image](https://user-images.githubusercontent.com/24581080/101281219-ec338980-37de-11eb-9962-e3da90b2574c.png)  вот такого сударя, но наклонить на 90 градусов и сделать под цвет монеты + упростить под общий стиль)

Череп с красной аурой(индикатор на против хп что воин мертв и не может ничего делать)

**Comment by mihailvityaev** [comment]
сердце:
![сердечко](https://user-images.githubusercontent.com/68809237/101607140-4584fe00-3a15-11eb-9d0c-4b58f0abc9f0.png)

**Comment by mihailvityaev** [comment]
меч: 
![1 меч](https://user-images.githubusercontent.com/68809237/101607578-cfcd6200-3a15-11eb-9302-ce1aa5c38a70.png)

**Comment by mihailvityaev** [comment]
Латы:
![доспехи3](https://user-images.githubusercontent.com/68809237/101614096-9567c300-3a1d-11eb-92ca-7797da1c464b.png)

**Comment by mihailvityaev** [comment]
монетка
![монета2](https://user-images.githubusercontent.com/68809237/101616024-e4165c80-3a1f-11eb-8cc2-5cf922eb0e18.png)

**Comment by mihailvityaev** [comment]
дракончик:

![дракончик4](https://user-images.githubusercontent.com/68809237/101629802-f51c9900-3a32-11eb-9784-cab622289468.png)

**Comment by mihailvityaev** [comment]
череп:

![череп4](https://user-images.githubusercontent.com/68809237/101633839-e76a1200-3a38-11eb-8f54-2f61dd8f85c0.png)
